### PR TITLE
fix(toEnglish): properly detect word boundaries

### LINKED ISSUE #175: `toEnglish` word endings not stripped correctly
**Describe the bug**
toEnglish( 'ਹਰਿ ਹਰਿ' ) => `har hari` surely should just go to `har har` 

```
console.log(toEnglish( toUnicode('siqguru siqguru' ))) => "satigur satiguru"
```

### PR DESCRIPTION
**Pull request by bhajneet**
Fixes #175

### Summary

Found this bug while @Harjot1Singh was working on single word translits in presenter

### Tests for unexpected behavior

All old tests pass, as do these new ones:

```
  [ 'ਹਰਿ', 'har' ],
  [ 'ਸਚੁ', 'sach' ],
  [ 'ਰਾਹੁ', 'raahu' ],
  [ 'ਭਾਉ', 'bhaau' ],
  [ 'ਸਤਿਗੁਰੁ ਸਤਿਗੁਰੁ ਸਚੁ; ਸਚੁ ਹਰਿ ਹਰਿ ਹਿੰਙੁ', 'satigur satigur sach; sach har har hing' ],
  [ 'ਸੁ ਉ ਜੁ', 'su u ju' ],
```

### Time spent on PR
one hour

### Reviewers
@Harjot1Singh @Sarabveer

### CODE REVIEW

**Review by Harjot1Singh — APPROVED** [review]
Looks good to me and the test case coverage is sufficient. @Sarabveer if you can take a look today to confirm, that'd be good, I'll merge at EOD.

**Review by Sarabveer — CHANGES_REQUESTED** [review]
https://github.com/shabados/gurmukhi-utils/blob/f0a2bfae4a927306f5a9670ea3d39eb06f8c13e5/lib/toShahmukhi.js#L108

This would also need to be updated.

**Comment by bhajneet** [comment]
Since you implemented that and we are not quite fluent in it, perhaps you can propose something more concrete/actionable?

Else you can file an issue and do it later

**Comment by bhajneet** [comment]
> 
> 
> https://github.com/shabados/gurmukhi-utils/blob/f0a2bfae4a927306f5a9670ea3d39eb06f8c13e5/lib/toShahmukhi.js#L108
> 
> This would also need to be updated.

Perhaps best to open a new issue for you to work on, I don't know how to fix the tests on this

image

Please allow this PR to be merged in for the time being

**Comment by Harjot1Singh** [comment]
Moved to #180 and releasing as is.

**Pull request merged**
