### PR TITLE
docs: add third party port

### PR DESCRIPTION
**Pull request by bhajneet**
### Summary of PR
Added a third party ports section

### Time spent on PR
5 minutes

### Reviewers
@Harjot1Singh

### CODE REVIEW

**Comment by saihaj** [comment]
@bhajneet we need to sync this in docs repo too?

**Comment by bhajneet** [comment]
> 
> 
> @bhajneet we need to sync this in docs repo too?

Where is this synced in the docs repo?

**Comment by saihaj** [comment]
> > 
> 
> > 
> 
> > @bhajneet we need to sync this in docs repo too?
> 
> 
> 
> Where is this synced in the docs repo?

Yes. https://github.com/shabados/docs/pull/15

**Comment by bhajneet** [comment]
So it looks like you're still discussing it there with Harjot. I think this PR can go in without needing to resolve that right away

**Comment by saihaj** [comment]
I guess Harjot forgot to reply 
and I also forgot to ping back. I will sync this one once this gets merged here. Definitely we need a better way to sync docs.

**Comment by Harjot1Singh** [comment]
I'd probably rename it to community instead of 3rd party, but not fussed. Change as you see fit, will approve now and LGTM

**Review by Harjot1Singh — APPROVED** [review]

**Pull request merged**
