### PR TITLE
fix(toEnglish): add passthrough for letters that are not in the transliteration map

### PR DESCRIPTION
**Pull request by Harjot1Singh**

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
@bhajneet @Sarabveer this should fix SGPC builds, but I do not know if this is desirable

**Comment by bhajneet** [comment]
What about https://github.com/ShabadOS/gurmukhi-utils/blob/b256c3e9222d46a649da6838297df0600a59ec5d/lib/toEnglish.js#L13 pass through section?

**Comment by bhajneet** [comment]
@Sarabveer mind as well add the transliterations for the two characters you've added to the font as well

**Comment by Harjot1Singh** [comment]
Yeah we can add them into passthrough, but we should have a default behaviour (which I’m guessing is suppression actually lol) rather than just crashing.

**Pull request merged**
